version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mern-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mern-ecommerce
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mern-ecommerce
      - ORIGIN=http://localhost:3000
      - EMAIL=test@example.com
      - PASSWORD=testpassword
      - LOGIN_TOKEN_EXPIRATION=30d
      - OTP_EXPIRATION_TIME=120000
      - PASSWORD_RESET_TOKEN_EXPIRATION=2m
      - COOKIE_EXPIRATION_DAYS=30
      - SECRET_KEY=mern-secret-key-2024
      - PRODUCTION=false
    depends_on:
      - mongodb
    networks:
      - mern-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - mern-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge