apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-ecommerce
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: filiplozanoski/mern-ecommerce-backend:latest
        ports:
        - containerPort: 8000
        env:
        # Основни конфигурации
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: PORT
        # MongoDB конфигурација
        - name: MONGO_URI
          value: "mongodb://admin:password123@mongodb-service.mern-ecommerce.svc.cluster.local:27017/mern-ecommerce?authSource=admin"
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: MONGODB_PORT
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: MONGODB_DATABASE
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: MONGODB_PASSWORD
        # JWT конфигурација
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: JWT_REFRESH_SECRET
        # Email/SMTP конфигурација
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: SMTP_PORT
        - name: SMTP_SECURE
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: SMTP_SECURE
        - name: FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: mern-app-config
              key: FROM_EMAIL
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: mern-app-secrets
              key: SMTP_PASS
        # Други
        - name: OTP_EXPIRATION_TIME
          value: "600000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"