apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-app-ingress
  namespace: mern-ecommerce
  labels:
    app: mern-ecommerce
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
  - host: mern-ecommerce.local
    http:
      paths:
      # Backend API рути - без rewrite
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      # Frontend рути
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80